console.group("Cuadrado");
const ladocuadrado = 5;
console.log("los lados del cuadrado miden: "+ladocuadrado+"cm");
const perimetrocuadrado = ladocuadrado * 4;
console.log("el perimetro del cuadrado es: "+perimetrocuadrado+"cm");
const areacuadrado = ladocuadrado * ladocuadrado;
console.log("el área del cuadrado es: "+areacuadrado+"cm al cuadrado");
console.groupEnd();

console.group("Triangulo");
const ladotriangulo1 = 6;
const ladotriangulo2 = 6;
const ladotriangulo3 = 4;
const alturatriangulo= 5.5;
console.log("los lados del triangulo miden: "+ladotriangulo1+"cm, "+ladotriangulo2+"cm y "+ladotriangulo3+"cm");
const perimetrotriangulo= ladotriangulo1+ladotriangulo2+ladotriangulo3;
console.log("el perimetro del triangulo es: "+perimetrotriangulo+"cm");
const areatriangulo= (ladotriangulo3*alturatriangulo)/2;
console.log("el área del triangulo es: "+areatriangulo+"cm al cuadrado");
console.groupEnd();

console.group("Circulo");
const radiocirculo = 4;
const diametro = radiocirculo*2;
const pi = Math.PI;
const perimetrodelcirculo= diametro*pi;
const areacirculo= (radiocirculo*radiocirculo)*pi ;
console.log("el radio del circulo mide: "+radiocirculo+"cm");
console.log("el diametro del circulo mide: "+diametro+"cm");
console.log("pi es: "+pi);
console.log("el perimetro del circulo mide: "+perimetrodelcirculo+"cm");
console.log("el área del circulo es: "+areacirculo+"cm al cuadrado");
console.groupEnd();
